source 'https://rubygems.org'

ruby '2.0.0'

gem 'rails', '4.0.0'

gem 'coffee-rails', '~> 4.0.0'
gem 'haml'
gem 'jquery-rails'
gem 'neo4j', github: 'andreasronge/neo4j'
gem 'octokit'
gem 'sass-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'

group :development, :test do
  gem 'spring'
  gem 'pry-rails'
end
