source 'https://rubygems.org'

ruby '2.1.2'

gem 'rails', '4.0.0'

gem 'coffee-rails', '~> 4.0.0'
gem 'faraday-http-cache'
gem 'haml'
gem 'jquery-rails'
gem 'neo4j', github: 'andreasronge/neo4j'
gem 'octokit'
gem 'sass-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'

group :development do
  gem 'spring'
  gem 'spring-commands-rspec'
  gem 'rubocop'
  gem 'quiet_assets'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'guard'
  gem 'guard-rspec'
  gem 'terminal-notifier-guard', '~> 1.5.3'
end

group :development, :test do
  gem 'rspec-rails'
  gem 'factory_girl_rails'
  gem 'jazz_hands', github: 'nixme/jazz_hands', branch: 'bring-your-own-debugger'
  gem 'pry-byebug'
  gem 'pry-coolline'
end

group :test do
  gem 'ffaker'
end
