source 'https://rubygems.org'

ruby '2.1.1'

gem 'rails', '4.0.3'
gem 'neo4j', github: 'andreasronge/neo4j'

gem 'sass-rails', '~> 4.0.1'
gem 'haml'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'

group :development do
  gem 'spring'
  gem 'pry-rails'
end
