source 'https://rubygems.org'

ruby '2.1.2'

gem 'rails', '4.1.1'

gem 'dotenv-rails', :groups => [:development, :test]

gem 'coffee-rails', '~> 4.0.1'
gem 'faraday-http-cache'
gem 'haml'
gem 'jquery-rails'
gem 'naught'
gem 'neo4j', github: 'andreasronge/neo4j'
gem 'octokit'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'

group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'guard'
  gem 'guard-bundler', require: false
  gem 'guard-rails', require: false
  gem 'guard-rspec', require: false
  gem 'guard-rubocop', require: false
  gem 'quiet_assets'
  gem 'spring'
  gem 'spring-commands-rspec'
  gem 'terminal-notifier-guard', require: false
end

group :development, :test do
  gem 'factory_girl_rails'
  gem 'jazz_hands', github: 'nixme/jazz_hands', branch: 'bring-your-own-debugger'
  gem 'pry-byebug'
  gem 'pry-coolline'
  gem 'rspec-rails'
  gem 'rubocop'
  gem 'rubocop-rspec'
end

group :test do
  gem 'ffaker'
  # gem 'fuubar', github: 'thekompanee/fuubar'
  gem 'rspec-its'
  gem 'vcr'
  gem 'webmock'
end
